name: task
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  uuid: ^3.0.5
  path_provider: ^2.0.5

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.2.4

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_color.png"
  adaptive_icon_background: "assets/logo/background.png"

flutter_native_splash:
  image: assets/logo/logo.png
  background_image: assets/logo/background.png

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/svg/
